name: Logger Test

on: 
  push:
    branches: [ main ]
    paths: ./**

defaults:
  run:
    working-directory: ./

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-recret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: 14.x
          check-latest: true
      - name: Install Dependencies
        run: |
          yarn --production
          pip install wheel --upgrade --user
          pip install awscli --upgrade --user
      - name: Deploy
        env:
          AWS_STACK_NAME: LoggerTest
          AWS_S3_BUCKET: ${{ secrets.AWS_DEPLOY_BUCKET_PROD }}
          AWS_S3_BUCKET_PREFIX: loggertest
        run: |
          aws cloudformation package \
            --template-file template.yml
            --s3-prefix $AWS_S3_BUCKET_PREFIX \
            --output-template-file package.yml \
            --s3-bucket $AWS_S3_BUCKET
          aws cloudformation deploy \
            --template-file package.yml
            --stack-name $AWS_STACK_NAME \
            --capabilities CAPABILITY_IAM