AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: Logger Test

Resources:
  LogDestinations:
    Type: AWS::Logs::Destination
    Properties:
      DestinationName: !GetAtt S3DeliveryStream.DeliveryStreamName
      TargetArn: !GetAtt S3DeliveryStream.Arn
  S3DeliveryStream:
    Type: AWS::KinesisFirehose::DeliveryStream
    DeliveryStreamName: log-stream-11272021
    DeliveryStreamType: DirectPut
    ExtendedS3DestinationConfiguration:
      BucketARN: arn:aws:s3:::log-bucket-11172021
      BufferingHints:
        SizeInMbs: 128
        IntervalInSeconds: 900
      CompressionFormat: UNCOMPRESSED
      ErrorOutputPrefix: table/error/!{firehose:error-output-type}/dt=!{timestamp:yyyy'-'MM'-'dd'}/h=!{timestamp:HH}/
      Prefix: YYYY=!{partitionKeyFromQuery:YYYY}/MM=!{partitionKeyFromQuery:MM}//DD=!{partitionKeyFromQuery:DD}/HH=!{partitionKeyFromQuery:HH}/REGION=!{partitionKeyFromQuery:REGION}/SITEID=!{partitionKeyFromQuery:SITEID}/
      RoleARN: arn:aws:iam::201768851286:role/KinesisFirehoseServiceRole
      DynamicPartitioningConfiguration:
        Enabled: true
        RetryOptions:
          DurationInSeconds: 300
      ProcessingConfiguration:
        Enabled: true
        Processors:
        - Type: MetadataExtraction
          Parameters:
          - ParameterName: MetadataExtractionQuery
            ParameterValue: '{YYYY : (.ts/1000) | strftime("%Y"), MM : (.ts/1000)
              | strftime("%m"), DD : (.ts/1000) | strftime("%d"), HH: (.ts/1000)
              | strftime("%H")}'
          - ParameterName: JsonParsingEngine
            ParameterValue: JQ-1.6
        - Type: AppendDelimiterToRecord
          Parameters:
          - ParameterName: Delimiter
            ParameterValue: "\\n"

  LoggerLambda:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Ref AWS::StackName
      CodeUri: ./
      Handler: index.handler
      Runtime: nodejs14.x
      Timeout: 60
      MemorySize: 1024
      Environment:
        Variables:
          NODE_ENV: production
      Events:
        Api:
          Type: Api
          Properties:
            Path: /v1/logger
            Method: GET
        Api2:
          Type: Api
          Properties:
            Path: /v1/test
            Method: POST
