AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: Logger Test

Parameters:
  DestinationName:
    Type: String
    Default: "LogDestination"
 
Resources:
  LogDestinations:
    DependsOn: S3DeliveryStream
    Type: AWS::Logs::Destination
    Properties:
      DestinationName: 
        Ref: DestinationName
      RoleArn: "arn:aws:iam::201768851286:role/CWLtoKinesisFirehoseRole"
      TargetArn: !GetAtt S3DeliveryStream.Arn
      DestinationPolicy: |
        {
          "Version" : "2012-10-17",
          "Statement" : [
            {
              "Effect" : "Allow",
              "Principal" : {
                "AWS" : "201768851286"
              },
              "Action" : "logs:PutSubscriptionFilter", 
              "Resource" : "arn:aws:logs:us-east-1:201768851286:destination:LogDestination"
            }
          ]
        }
        
  # LogSubscriptionFilter:
  #   DependsOn: S3DeliveryStream
  #   Type: AWS::Logs::SubscriptionFilter
  #   Properties: 
  #     DestinationArn: "arn:aws:firehose:us-east-1:201768851286:deliverystream/log-stream-11272021"
  #     FilterPattern: ""
  #     LogGroupName: !Sub '/aws/lambda/${LoggerLambda}'
  #     RoleArn: "arn:aws:iam::201768851286:role/CWLtoKinesisFirehoseRole"

  S3DeliveryStream:
    Type: AWS::KinesisFirehose::DeliveryStream
    Properties:
      DeliveryStreamName: log-stream-11272021
      DeliveryStreamType: DirectPut
      S3DestinationConfiguration:
        BufferingHints:
            SizeInMBs: 128
            IntervalInSeconds: 5
        BucketARN: arn:aws:s3:::log-bucket-11172021
        RoleARN: "arn:aws:iam::201768851286:role/FirehosetoS3Role"
        
  LoggerLambda:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Ref AWS::StackName
      CodeUri: ./
      Handler: index.handler
      Runtime: nodejs14.x
      Timeout: 60
      MemorySize: 1024
      Environment:
        Variables:
          NODE_ENV: production
      Events:
        Api:
          Type: Api
          Properties:
            Path: /v1/logger
            Method: GET
        Api2:
          Type: Api
          Properties:
            Path: /v1/test
            Method: POST
