AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: Logger Test

Resources:
  LoggerLambda:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Ref AWS::StackName
      CodeUri: ./
      Handler: index.handler
      Runtime: nodejs14.x
      Timeout: 60
      MemorySize: 1024
      Environment:
        Variables:
          NODE_ENV: production
      Events:
        Api:
          Type: Api
          Properties:
            Path: /v1/logger
            Method: GET
        Api2:
          Type: Api
          Properties: 
            Path: /v1/test
            Method: POST